version: "3.9"

networks:
  app-net:
    driver: bridge
  monitoring-net:
    driver: bridge

services:
  backend:
    container_name: backend-${ENV}          # backend-dev or -prod
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: deepdiv/backend:${ENV}            # image tagged by environment
    expose:                                  # Do not give Ports, it makes it publically reachable
      - "8000"                               # ⛔ NOT exposed to host
    environment:
      ENV: ${ENV}
      PYTHONPATH: /app
    networks:
      - app-net
      - monitoring-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

  frontend:
    container_name: frontend-${ENV}          # frontend-dev or frontend-prod
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: deepdiv/frontend:${ENV}           # image tagged by environment
    expose:
      - "8501"
    environment:
      ENV: ${ENV}
      BACKEND_SERVICE_URL: http://backend:8000   # Internal service-to-service call used in frontend code 
      PYTHONPATH: /app
    networks:
      - app-net
      - monitoring-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  nginx:
    container_name: nginx-${ENV}              # nginx-dev or nginx-prod
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: deepdiv/nginx:${ENV}               # image tagged by environment
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-net
      - monitoring-net
    depends_on:
      - backend
      - frontend
    environment:
      ENV: ${ENV}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=/prometheus/'  # This is the key fix
      - '--web.route-prefix=/prometheus/'
    expose:
      - "9090"                               # ⛔ internal only
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    expose:
      - "3000"                                # ⛔ accessed via VPN / reverse proxy
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    depends_on:
      - prometheus
    networks:
      - monitoring-net
      
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    expose:
      - "9100"                                # ⛔ never exposed to host
    networks:
      - monitoring-net
