version: "3.9"

services:
  app:
    build: .
    image: cold-email-app
    ports:
      - "8501:8501"
    environment:
      PYTHONPATH: /Cold-Email-Automation
    volumes:
      - app_data:/Cold-Email-Automation/app   # named volume

volumes:
  app_data:
