version: "3.9"

services:
  backend:
    container_name: backend-${ENV}          # backend-dev or -prod
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: deepdiv/backend:${ENV}          # image tagged by environment
    ports:
      - "8000:8000"
    environment:
      ENV: ${ENV}
      PYTHONPATH: /app
    networks:
      - monitoring
  
  frontend:
    container_name: frontend-${ENV}          # backend-dev or -prod
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: deepdiv/frontend:${ENV}          # image tagged by environment
    ports:
      - "8501:8501"
    environment:
      ENV: ${ENV}
      PYTHONPATH: /app
    networks:
      - monitoring

  nginx:
    container_name: nginx-${ENV}       # nginx-dev or nginx-prod
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: deepdiv/nginx:${ENV}        # image tagged by environment
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENV: ${ENV}
    networks:
      - monitoring

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus-${ENV}
#     volumes:
#       - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"
#     environment:
#       ENV: ${ENV}
#     networks:
#       - monitoring

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana-${ENV}
#     ports:
#       - "3000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_PASSWORD=Admin123
#     depends_on:
#       - prometheus
#     networks:
#       - monitoring

#   node-exporter:
#     image: prom/node-exporter:latest
#     container_name: node-exporter-${ENV}
#     ports:
#       - "9100:9100"
#     environment:
#       ENV: ${ENV}
#     networks:
#       - monitoring

networks:
  monitoring:
    driver: bridge
