version: "3.9"

services:
  app:
    build: .
    image: cold-email-app
    ports:
      - "8501:8501"                 # host:container port mapping
    environment:
      PYTHONPATH: /Cold-Email-Automation
