version: "3.9"

networks:
  app-net:
    driver: bridge
  monitoring-net:
    driver: bridge

services:
  backend:
    container_name: backend-${ENV}          # backend-dev or -prod
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: deepdiv/backend:${ENV}          # image tagged by environment
    expose:                                # Do not give Ports, it makes it publically reachable
      - "8000"                             # â›” NOT exposed to host 
    environment:
      ENV: ${ENV}
      PYTHONPATH: /app
    networks:
      - app-net
      - monitoring-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  frontend:
    container_name: frontend-${ENV}          # backend-dev or -prod
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: deepdiv/frontend:${ENV}          # image tagged by environment
    expose:
      - "8501"
    environment:
      ENV: ${ENV}
      BACKEND_SERVICE_URL: http://backend:8000       # Internal call Service A to Service B without API gateway
      PYTHONPATH: /app
    networks:
      - app-net
      - monitoring-net

  nginx:
    container_name: nginx-${ENV}       # nginx-dev or nginx-prod
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: deepdiv/nginx:${ENV}        # image tagged by environment
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend 
        condition: service_healthy
    environment:
      ENV: ${ENV}
    networks:
      - app-net
      - monitoring-net

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus-${ENV}
    volumes:
      - ./monitoring-net/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      ENV: ${ENV}
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana-${ENV}
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Admin123
    depends_on:
      - prometheus
    networks:
      - monitoring-net

  node-exporter:
    image: prom/node-exporter:1.10.2
    container_name: node-exporter-${ENV}
    ports:
      - "9100:9100"
    environment:
      ENV: ${ENV}
    networks:
      - monitoring-net

