global:
  scrape_interval: 15s          # how often to scrape metrics
  evaluation_interval: 15s      # how often to evaluate rules

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']
      
  # - job_name: node-exporter
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['node-exporter:9100']
