version: "3.9"

services:
  app:
    container_name: cold-email-app-container 
    build:
      context: ..                     # go one folder up from docker/ â†’ Cold-Email-Automation/
      dockerfile: docker/Dockerfile
    image: deepdiv/cold-email-app:latest
    ports:
      - "8501:8501"                  
    environment:
      PYTHONPATH: /Cold-Email-Automation

  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    image: deepdiv/cold-email-nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - app

